import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ConvexClientProvider } from '@/components/providers/ConvexClientProvider';
import Navbar from '@/components/Navbar';

import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from '@/components/providers/ThemeProvider';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
});

export const metadata: Metadata = {
	title: 'Ultimate Stripe Integration',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning >
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
			>
				<ConvexClientProvider>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
					<div className="absolute inset-0 -z-10 h-full w-full bg-white dark:bg-gray-800 bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem] dark:bg-none">
						<div className="absolute bottom-0 left-0 right-0 top-0 bg-[radial-gradient(circle_800px_at_100%_200px,#d5c5ff,transparent)]"></div>
					</div>
					<Navbar />
					{children}
          <Toaster />
          </ThemeProvider>
				</ConvexClientProvider>
			</body>
		</html>
	);
}
